### ISSUE TITLE
Multiple language to switch between languages

### ISSUE THREAD

**Issue by lmmrssa** [ole-vi/planet#287]
- [x] Make a json file which can be used by installation script and also from the planet application itself
- [ ] File should follow the structure of language
  ```
  short_code: *Format ISO 639-3
  name:
  flag: *Graphical image
  served_url:
  active:
  ```
- [ ] Make a language switch option within application. 
_For now it should just give the option to click but not actually translate, later it will switch to different application AOT based on language_
